// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhwirzscpmunyygmhmhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpod2lyenNjcG11bnl5Z21obWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzAxNjcsImV4cCI6MjA2MDQwNjE2N30.1-TSH6r8QSwlAug3ntPiH1xrRgfLPqHTh8_Uk5VySS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);